config/routes.rb
Rails.application.routes.draw do
  root to: 'showcase#index'

  namespace :store do
    resources :products
    mount EssentialSelling::Engine => "/"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include EssentialSelling::CurrentOrder
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
  def index
    @showcase_blocks = EssentialSelling::ShowcaseBlock.limit(5)
  end
end

app/controllers/store/products_controller.rb
class Store::ProductsController < ApplicationController
  respond_to :html, :json

  def show
    respond_with resource
  end
  
  private
  
  helper_method def collection
    @products ||= EssentialSelling::Product.includes(:photos, :variants, taxons: :translations, extras: :translations)
  end
  
  helper_method def resource
    @product ||= collection.where(slug: params[:id]).first!
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def uploadcare_url(uid)
    "http://www.ucarecdn.com/#{uid}/"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>O2s</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= html_import_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body unresolved class="background-sensitive">

<aux-layers>
  <div>
    <%= yield %>
  </div>
  <aux-layout modules="12">
    <aux-layout-cell width="4">
      <%= link_to t('.shop'), root_path %>
      <%= link_to t('.about'), root_path %>
      <%= link_to t('.blog'), root_path %>
    </aux-layout-cell>
    <aux-layout-cell width="3" gap="4" >
      <%= link_to image_tag('osome2some.svg'), root_path %>
    </aux-layout-cell>
  </aux-layout>
</aux-layers>

<!-- <aux-background-check targets=".background-sensitive" images=".background-image"></aux-background-check> -->

</body>
</html>

app/views/showcase/index.html.erb
<% @showcase_blocks.each do |block| %>
  <% style = block.style.dasherize %>
  <es-showcase-<%= style %> image="<%= uploadcare_url block.images %>" video="<%= block.video_url %>">
    <% if block.title.present? %>
      <h1 title>
        <%= block.title %>
      </h1>
    <% end %>
    <% if block.subtitle.present? %>
      <h2 subtitle>
        <%= block.subtitle %>
      </h2>
    <% end %>
    <% if block.text.present? %>
      <content>
        <%= block.text %>
      </content>
    <% end %>
    <% if block.link_text.present? && block.link.present? %>
      <%= link_to block.link_text, block.link %>
    <% end %>
  </es-showcase-<%= style %>>
<% end %>

app/views/store/products/show.html.erb
<polymer-element name="o2s-order-item" attributes="">
  <script>
    Polymer({
      created: function(){
        this.options = []
      }
    });
  </script>
</polymer-element>

<template is="auto-binding">
  <aux-resource id="resource" url="<%= store_product_url(resource) %>"></aux-resource>

  <o2s-order-item id="order"></o2s-order-item>
  
  <o2s-photo-filter id="filteredPhotos" input="{{$.resource.response.photos}}">
    <aux-filter-context name="options" value="{{$.order.options}}"></aux-filter-context>
  </o2s-photo-filter>

  <aux-map id="photoIds" input="{{$.filteredPhotos.objects}}" expression="element.url"></aux-map>
  
  <aux-layers>
    <o2s-slider ids="{{$.photoIds.objects}}"></o2s-slider>
    <aux-layout modules="3" class="o2s-product-store">
      <aux-layout-cell width="1" gap="2">
        <h1><%= resource.title %></h1>
    
        <p class="lead"><%= number_to_currency resource.price %></p>
    
        <%= resource.info %>

        <%= form_for current_order.items.build, url: [store_essential_selling, :api, current_order, :items], remote: true do |form| %>
          <% resource.available_charachteristics.each do |c| %>
            <%= form.collection_select :option_ids,
              c.options & resource.available_options,
              :id, :title, {prompt: 'Select'}, {value: raw("{{ $.order.options[#{c.id}] }}")}
            %>
          <% end %>

          <%= form.collection_check_boxes :extra_ids, resource.extras, :id, :title do |b| %>
            <p>
              <%= b.label {b.check_box + ' ' + b.text} %>
              <br>
              <%= b.object.info %>
            </p>
        
          <% end %>

          <%= form.number_field :count %>
      
          <%= form.submit %>
        <% end %>
      </aux-layout-cell>
    </aux-layout>
  </aux-layers>
</template>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>